<a href="https://colab.research.google.com/github/lipeng2021/-python1/blob/main/%E6%A8%A1%E5%9E%8B%E7%9A%84%E4%BF%9D%E5%AD%98%E5%92%8C%E8%AF%BB%E5%8F%96.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

In [3]:
class MLP(nn.Module):
  def __init__(self):
    super(MLP,self).__init__()
    self.hidden = nn.Linear(3,2)
    self.act = nn.ReLU()
    self.output = nn.Linear(2,1)
  def forward(self,x):
    y = self.output(self.act(self.hidden(x)))
    return x
net = MLP()
print(net)
net.state_dict()

MLP(
  (hidden): Linear(in_features=3, out_features=2, bias=True)
  (act): ReLU()
  (output): Linear(in_features=2, out_features=1, bias=True)
)


OrderedDict([('hidden.weight', tensor([[-0.5087, -0.2554,  0.0137],
                      [-0.0377, -0.5522,  0.4578]])),
             ('hidden.bias', tensor([-0.5472, -0.1267])),
             ('output.weight', tensor([[ 0.2611, -0.5844]])),
             ('output.bias', tensor([-0.4768]))])

In [4]:
optimizer = torch.optim.SGD(net.parameters(),lr=0.001,momentum=0.9)
optimizer.state_dict()

{'param_groups': [{'dampening': 0,
   'lr': 0.001,
   'momentum': 0.9,
   'nesterov': False,
   'params': [0, 1, 2, 3],
   'weight_decay': 0}],
 'state': {}}

In [5]:
PATH = '/net_state_dict.pth'
x = torch.randn(2,3)
y = net(x)
torch.save(net.state_dict(),PATH)
net2 = MLP()
net2.load_state_dict(torch.load(PATH))
y2 = net2(x)
y2==y

tensor([[True, True, True],
        [True, True, True]])

In [6]:
import torch
import torch.nn as nn

In [9]:
class MLP(nn.Module):
  def __init__(self):
    super(MLP,self).__init__()
    self.hidden = nn.Linear(3,2)
    self.act = nn.ReLU()
    self.output = nn.Linear(2,1)
  def forward(self,x):
    y = self.output(self.act(self.hidden(x)))
    return x

In [10]:
net = MLP()
print(net)
net.state_dict()
optimizer = torch.optim.SGD(net.parameters(),lr=0.001,momentum=0.9)
optimizer.state_dict()

MLP(
  (hidden): Linear(in_features=3, out_features=2, bias=True)
  (act): ReLU()
  (output): Linear(in_features=2, out_features=1, bias=True)
)


{'param_groups': [{'dampening': 0,
   'lr': 0.001,
   'momentum': 0.9,
   'nesterov': False,
   'params': [0, 1, 2, 3],
   'weight_decay': 0}],
 'state': {}}

In [11]:
PATH = '/MLP.pth'
x = torch.randn(2,3)
y = net(x)
torch.save(net.state_dict(),PATH)

net2 = MLP()
net2.load_state_dict(torch.load(PATH))
y1 = net2(x)
y==y1

tensor([[True, True, True],
        [True, True, True]])

使用GPU进行计算

In [12]:
!nvidia-smi

Tue Apr 19 10:37:18 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8    34W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [13]:
torch.cuda.is_available()

True

In [14]:
torch.cuda.device_count()

1

In [15]:
torch.cuda.get_device_name()

'Tesla K80'

In [19]:
x = torch.randn(2,3)
print(x)
x = x.cuda()
print(x)
x.device

tensor([[-0.0025,  0.6062, -1.8068],
        [ 0.1075,  0.8474,  1.3085]])
tensor([[-0.0025,  0.6062, -1.8068],
        [ 0.1075,  0.8474,  1.3085]], device='cuda:0')


device(type='cuda', index=0)

In [21]:
device = torch.device('cuda' if torch.cuda.is_available()else 'cpu')
x = torch.randn(4,4,device=device)
print(x)
y = torch.randn(2,2).to(device)
print(y)

tensor([[ 2.0642, -0.5873,  1.0341, -0.2045],
        [ 0.6999,  0.0767,  0.7450,  1.1429],
        [ 0.6088,  0.7413,  0.3145, -0.4618],
        [ 0.7544, -1.1328,  1.0907, -1.2556]], device='cuda:0')
tensor([[ 0.4548,  0.5277],
        [-0.4956, -0.1839]], device='cuda:0')


In [24]:
net = nn.Linear(3,1)
list(net.parameters())[0].device
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)