<a href="https://colab.research.google.com/github/lipeng2021/-python1/blob/main/%E6%A8%A1%E5%9E%8B%E6%9E%84%E9%80%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.init as init

In [2]:
class MLP(nn.Module):
  def __init__(self,**kwargs):
    super(MLP,self).__init__()
    self.hidden = nn.Linear(784,256)
    self.act = nn.ReLU()
    self.output = nn.Linear(256,10)
  def forward(self,x):
    y = self.output(self.act(self.hidden(x)))
    return y

In [3]:
x = torch.rand(2,784)
net =MLP()
print(net)
net(x)

MLP(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (act): ReLU()
  (output): Linear(in_features=256, out_features=10, bias=True)
)


tensor([[ 0.1003,  0.3327, -0.2624,  0.1068, -0.0332,  0.2999, -0.0733, -0.0424,
         -0.0334,  0.0086],
        [ 0.1065,  0.3937, -0.3036,  0.0947, -0.0496,  0.3313, -0.0601, -0.0962,
          0.0670, -0.0234]], grad_fn=<AddmmBackward0>)

In [4]:
net1 = nn.Sequential(
    nn.Linear(784,256),
    nn.ReLU(),
    nn.Linear(256,10)
)

In [5]:
x = torch.rand(2,784)
print(net1)
net1(x)

Sequential(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=10, bias=True)
)


tensor([[ 0.1284, -0.0015,  0.1384, -0.0879, -0.0630, -0.0819, -0.2315,  0.3294,
          0.1394, -0.1326],
        [ 0.1279, -0.0411,  0.1881, -0.0106, -0.0058, -0.0950, -0.2629,  0.1619,
          0.1048, -0.2527]], grad_fn=<AddmmBackward0>)

In [6]:
from collections import OrderedDict
net2 = nn.Sequential(
    OrderedDict([
        ('hidden',nn.Linear(784,256)),
        ('act',nn.ReLU()),
        ('output',nn.Linear(256,10)),
    ])
)

In [7]:
x = torch.rand(2,784)
print(net2)
net2(x)

Sequential(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (act): ReLU()
  (output): Linear(in_features=256, out_features=10, bias=True)
)


tensor([[-0.1911, -0.1158,  0.0908,  0.0540,  0.0565, -0.1761,  0.1281,  0.0830,
         -0.1433, -0.0575],
        [-0.1449, -0.0501,  0.1540, -0.0054,  0.0503, -0.1702,  0.1484,  0.0709,
          0.0668, -0.1051]], grad_fn=<AddmmBackward0>)

In [8]:
net4 = nn.ModuleList([nn.Linear(784,256),nn.ReLU()])
net4.append(nn.Linear(256,10))

ModuleList(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=10, bias=True)
)

In [9]:
x = torch.rand(2,784)
print(net4)

ModuleList(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=10, bias=True)
)


In [10]:
net5 = nn.ModuleDict(
    {
        'hidden':nn.Linear(784,256),
        'act':nn.ReLU()
    }
)
net5['output'] = nn.Linear(256,10)
print(net5)
print(net5['act'])

ModuleDict(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (act): ReLU()
  (output): Linear(in_features=256, out_features=10, bias=True)
)
ReLU()


In [11]:
net = nn.Sequential(
    nn.Linear(4,3),
    nn.ReLU(),
    nn.Linear(3,1)
    )
print(net)
x = torch.rand(2,4)
y=net(x).sum()
print(y)

Sequential(
  (0): Linear(in_features=4, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)
tensor(-0.1632, grad_fn=<SumBackward0>)


In [12]:
print(type(net.named_parameters()))
for name,param in net.named_parameters():
  print(name,param.size())

<class 'generator'>
0.weight torch.Size([3, 4])
0.bias torch.Size([3])
2.weight torch.Size([1, 3])
2.bias torch.Size([1])


In [13]:
for name,param in net.named_parameters():
  if 'weight' in name:
    init.normal_(param,mean=0,std=0.01)
    #print(param)
  if 'bias' in name:
    init.constant_(param,val=0)
    print(name,param.data)

0.bias tensor([0., 0., 0.])
2.bias tensor([0.])


自定义初始化方法

In [14]:
def normal_(tensor,mean=0,std=1):
  with torch.no_grad():
    return tensor.normal_(mean,std)

In [15]:
def init_weight_(tensor):
  with torch.no_grad():
    tensor.uniform_(-10,10)
    print(tensor.uniform_(-10,10))
    tensor*=(tensor.abs()>=5).float()
for name,param in net.named_parameters():
  if 'weight' in name:
    init_weight_(param)
    print(name,param.data)

Parameter containing:
tensor([[ 9.8035,  7.3941, -6.3200,  4.7369],
        [ 2.7777,  1.9657,  8.3675, -0.0401],
        [-9.8950,  0.6667, -9.6167,  6.0028]], requires_grad=True)
0.weight tensor([[ 9.8035,  7.3941, -6.3200,  0.0000],
        [ 0.0000,  0.0000,  8.3675, -0.0000],
        [-9.8950,  0.0000, -9.6167,  6.0028]])
Parameter containing:
tensor([[-2.1296,  6.0269,  2.0759]], requires_grad=True)
2.weight tensor([[-0.0000, 6.0269, 0.0000]])


In [30]:
linear = nn.Linear(1,1,bias=False)
net8 = nn.Sequential(linear,linear,linear,linear)
for name,param in net8.named_parameters():
  init.constant_(param,val=2)
  print(name,param.data)

0.weight tensor([[2.]])


In [31]:
x=torch.ones(1,1)
print(net8(x))
net8.zero_grad()
y = net8(x).sum()
print(y)

y.backward()
print(net8[0].weight.grad)
print(net8[1].weight.grad)

tensor([[16.]], grad_fn=<MmBackward0>)
tensor(16., grad_fn=<SumBackward0>)
tensor([[32.]])
tensor([[32.]])


In [39]:
x = torch.ones(2,1)
y = x+2
z = y*y*2
class Mylinear(nn.Module):
  def __init__(self) -> None:
      super(Mylinear,self).__init__()
  def forward(self,x):
    y = (x+2)**2*2
    return y

In [53]:
x = torch.ones(2,2,requires_grad=True)
print(x)
net = Mylinear()
print(net)
y=net(x).sum()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Mylinear()
None


In [56]:
import torch

x = torch.ones((2,2),requires_grad=True)
print("x>>>",x)

y = x+2
z = y*y*3
out = z.mean()
print("out>>>",out)
out.backward()
print("x.grad>>>",x.grad)

x>>> tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
out>>> tensor(27., grad_fn=<MeanBackward0>)
x.grad>>> tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [58]:
class CenteredLayer(nn.Module):
  def __init__(self,**kwargs):
    super(CenteredLayer,self).__init__()
  def forward(self,x):
    return x-x.mean()

In [60]:
x = torch.tensor([1,2,3,4,5],dtype=torch.float)
net = CenteredLayer()
net(x)

tensor([-2., -1.,  0.,  1.,  2.])

In [61]:
net1 = nn.Sequential(nn.Linear(8,128),CenteredLayer())
y = net1(torch.rand(4,8))
print(y.mean().item())

0.0


In [ ]:
class MyDense(nn.Module):
  def __init__(self):
    super(MyDense,self).__init__()
    self.params = nn.ParameterList([nn.Parameter(torch.randn(4,4))for i in range(3)])
    self.params.append(nn.Parameter(torch.randn(4,1)))
  def forward(self,x):
    for i in range(len(self.params)):
      print(len(self.params))
      x = torch.mm(x,self.params[i])
    return x
net = MyDense()
print(net)
x = torch.ones(4,4)
net(x)

In [72]:
class MyDictDense(nn.Module):
  def __init__(self):
    super(MyDictDense,self).__init__()
    self.params = nn.ParameterDict({
        'linear1':nn.Parameter(torch.randn(4,4)),
        'linear2':nn.Parameter(torch.randn(4,1)),
    })
    self.params['linear3'] = nn.Parameter(torch.randn(4,2))
  def forward(self,x,choice='linear1'):
    return torch.mm(x,self.params[choice])
net = MyDictDense()
print(net)
x = torch.randn(1,4)
net(x,choice='linear2')
net(x,choice='linear1')
net(x,choice='linear3')

MyDictDense(
  (params): ParameterDict(
      (linear1): Parameter containing: [torch.FloatTensor of size 4x4]
      (linear2): Parameter containing: [torch.FloatTensor of size 4x1]
      (linear3): Parameter containing: [torch.FloatTensor of size 4x2]
  )
)


tensor([[-3.8823,  0.1533]], grad_fn=<MmBackward0>)

In [79]:
x = torch.ones(3)
torch.save(x,'/x.pt1')
x2 = torch.load('/x.pt1')
print(x)

tensor([1., 1., 1.])
